apiVersion: v1
kind: Service
metadata:
  name: oci-exporter
  namespace: monitoring
  labels:
    app: oci-exporter
spec:
  type: ClusterIP
  selector:
    app: oci-exporter
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP