apiVersion: v1
kind: ServiceAccount
metadata:
  name: oci-exporter
  namespace: monitoring
  # annotations:
  #   # OKE Workload Identity (OCI IAM Workload Identity, if used instead of node InstancePrincipal):
  #   # oci.oraclecloud.com/workload-service-account-token: "true"